# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ~/.m2/settings.xml # location for the settings.xml file

    - name: Configure Maven
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/geovanaramos/*", "snapshots": { "enabled": "true" }}]'
        servers: '[{ "id": "github", "username": "GeovanaRamos", "password": "${{ secrets.INTERPRETER_TOKEN }}" }]'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.INTERPRETER_TOKEN }}
